# Название workflow, которое будет отображаться на вкладке Actions в GitHub
name: Code Checks

# Когда запускать этот workflow
on:
  push:                   # При пуше изменений
    branches: [ main ]    # Только если пушим в ветку main
  pull_request:           # При открытии или обновлении pull request
    branches: [ main ]    # Если PR направлен в ветку main

jobs:
  # -------------------------
  # JOB 1: Проверка стиля кода (lint)
  # -------------------------
  lint:
    runs-on: ubuntu-latest    # Запускаем job на Linux runner (виртуальной машине GitHub)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3    # Загружаем код из репозитория

      - name: Set up Python
        uses: actions/setup-python@v4   # Устанавливаем Python на runner
        with:
          python-version: '3.11'        # Указываем нужную версию Python

      - name: Install black
        run: |
          python -m pip install --upgrade pip   # Обновляем pip
          pip install black                     # Устанавливаем black для проверки стиля

      - name: Run black
        run: |
          black --check --diff --color .    # Проверяем, соответствует ли код стилю black
                                            # Если стиль нарушен — job упадёт (покажет ошибку)

  # -------------------------
  # JOB 2: Запуск тестов
  # -------------------------
  test:
    runs-on: ubuntu-latest
    needs: lint               # Запускаем этот job ТОЛЬКО если job lint прошёл успешно

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    # Обновляем pip
          pip install -r requirements.txt        # Устанавливаем зависимости из requirements.txt

      - name: Run pytest
        run: |
          pytest    # Запускаем тесты с помощью pytest
